### ISSUE TITLE
Request: renaming in UndoManager

### ISSUE THREAD

**Issue by eric-simonton-sama** [simontonsoftware/ng-app-state#12]
The names "oldState" and "newState" are confusing in `applyUndoState`, because during an undo "newState" is actually older than "oldState".

```ts
applyUndoState(
  newState: UndoStateType,
  batch: StoreObject<StateType>,
  undoOrRedo: UndoOrRedo,
  oldState: UndoStateType,
)
```

Suggest renaming to "stateToApply" and "stateToOverwrite"

**Comment by ersimont** [comment]
Done.
