### ISSUE TITLE
Fix order of subscribers

### ISSUE THREAD

**Issue by jrdioko** [simontonsoftware/ng-app-state#20]
We have a subscriber of an array that adds a subscription to elements of that array when deleting an element. An element subscriber appears to be firing before the owner subscriber.

This is happening with an `*ngFor` that should be deleting its child component, but the observable for the component is firing before it is deleted.

(further details discussed offline)

**Comment by eric-simonton-sama** [comment]
After some further investigation this is not an accurate description of the problem. More details are recorded elsewhere, but leaving this ticket open as a placeholder for now.

**Comment by ersimont** [comment]
It turns out the problem is around unsubscribing then resubscribing from the same store object. This should be fixed in the next release, which should happen whenever ngrx/store supports Angular 8.
